### ISSUE TITLE
MongoDBSources silently ignores non-existing database/collection

### ISSUE THREAD

**Issue by eminn** [hazelcast/hazelcast-jet-contrib#28]
In case when MongoDBSources has configured some database or collection which does not exist then it will not throw any Exception. I think that in most of time it indicates incorrect configuration and we should rather throw an Exception than just complete a job. At least for batch jobs. It is arguable for stream job since it can make sense in case when database/collection will be created after job was started, but we have to be sure that it will be able to really connect to that database/collection if it is started after job start (as I wrote above I was not able to test it).

**Comment by gurbuzali** [comment]
I don't think that this is a bug, MongoDB works just like IMDG when you call `get` on a database or collection, it creates them if does not exist. For example when you call `Sources.map(mapName)` on a non-created map, we don't throw exception, we actually create the map via `getMap(mapName)`.and since it is empty we just complete the job. Same is true for MongoDB, we actually create that database and/or collection while running the job.

We can actually check if a map exists by listing all data-structures and looking for the given map in the list. Same is true for MongoDB, we can check by listing all databases and collections. 

So the question, should we do it ?
