### ISSUE TITLE
Add Apache Pulsar connector

### ISSUE THREAD

**Issue by iamvvra** [hazelcast/hazelcast-jet-contrib#36]
Add source & sink connectors to `Apache Pulsar`.

I checked the provided reference implementations to write one - found the Kafka connector a similar one of `Pulsar`. Can I have Kafka connector as reference to write my `Pulsar` implementation? I went through the `AbstractProcessor` & `MetaSupplier` approaches of `Redis`, but unable to decide on the approach. 

Any reference, guides would help.

Thanks

**Comment by iamvvra** [comment]
Anything you would like to give me as reference if I should implement a Pulsar source connector?

**Comment by eminn** [comment]
You can have a look at [Kafka Connector](https://github.com/hazelcast/hazelcast-jet/tree/master/hazelcast-jet-kafka) here but it is much more complex since Kafka allows per-partition consumption. As far as I know Pulsar doesn't provide same capability so you don't need to create a task per partition and track their offsets.

My suggestion would be start with a small concrete example using SourceBuilder API like [Kafka Connect](https://github.com/hazelcast/hazelcast-jet-contrib/blob/master/kafka-connect/src/main/java/com/hazelcast/jet/contrib/connect/KafkaConnectSources.java) connector to achieve basic connection and message consumption from Pulsar. Then you can create a pull request and we can work on that together to evolve it to have fault-tolerance support. Otherwise as I have a limited working knowledge with Pulsar, it would be hard for me to give an advice for you. All I can say for now is to avoid Processor API and use SourceBuilder API because it is easy to make mistakes with that.
